image:
  repository: feelguuds/leads-scraper-service
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

config:
  redis:
    enabled: true
    dsn: "redis://:redis-local-dev@gmaps-scraper-leads-scraper-service-redis-master:6379/0"
    workers: 10
  scraper:
    webServer: true
    concurrency: 11
    depth: 5
    language: "en"
    searchRadius: 10000
    zoomLevel: 15
    fastMode: true

tests:
  enabled: false
  healthCheck:
    enabled: true
    path: "/health"
  configCheck:
    enabled: true

postgresql:
  enabled: true  # Enable PostgreSQL by default for local development
  auth:
    username: postgres
    password: postgres
    database: leads_scraper
    # PostgreSQL password will be stored in a secret
    existingSecret: ""
  primary:
    persistence:
      enabled: true
      size: 10Gi
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 1000m
        memory: 1Gi
    service:
      ports:
        postgresql: 5432
    # PostgreSQL configuration
    extraEnvVars:
      - name: POSTGRESQL_MAX_CONNECTIONS
        value: "100"
      - name: POSTGRESQL_SHARED_BUFFERS
        value: "128MB"

redis:
  enabled: true
  architecture: standalone
  auth:
    enabled: true
    password: "redis-local-dev"
  master:
    persistence:
      enabled: true
      size: 1Gi
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 256Mi
